/** Single place to edit Tobi's public identity, contact, and portfolio copy. */

export const SITE = {
  name: "Tobi",
  handle: "ox_tobiiii",
  title: "Tobi — Web3 Creator | Community | Content",
  description:
    "Web3 creator and community contributor. Ambassador at BestChange & Action Model. Official KOL at Bitget Wallet.",
  headline: "Web3 Creator, CT & Community",
  availability: "OPEN FOR WORK",
  availabilityNote: "OPEN TO OPPORTUNITIES",
  avatar: "/avatar.jpg",
  identities: [
    "Web3 Creator",
    "Content Creator",
    "Community Manager",
    "Ambassador",
    "KOL",
  ],
  tagline: "Web3 Creator • Content Creator • Community Manager",
  heroBody: `In Web3 since 2021. I make CT content, help communities grow, and work with teams as a creator, ambassador, and KOL.

Open for creator roles, community roles, internships, ambassador work, and collaborations.`,
  aboutTitle: "Who is Tobi?",
  about: `Started in Web3 in 2021 by learning ecosystems and following CT.

Now I ship content, show up in communities, and represent products I actually use — BestChange, Action Model, and Bitget Wallet.

Looking for teams that need a creator who can write, engage, and stay consistent.`,
  contact: {
    x: {
      label: "X / Twitter",
      handle: "ox_tobiiii",
      href: "https://x.com/ox_tobiiii",
      cta: "Message on X",
      hint: "Message me on X",
    },
    telegram: {
      label: "Telegram",
      handle: "@ox_tobiiii",
      href: "https://t.me/ox_tobiiii",
      cta: "Message on Telegram",
      hint: "Send me a Telegram message",
    },
    discord: {
      label: "Discord",
      handle: "ox_tobiiii",
      href: null as string | null,
      cta: "Copy Discord",
      hint: "Username — copy to clipboard",
    },
    email: {
      label: "Email",
      handle: "oxtobiiii@gmail.com",
      href: "mailto:oxtobiiii@gmail.com",
      cta: "Send Email",
      hint: "Send me an email",
    },
    youtube: {
      label: "YouTube",
      handle: "@oxtobiiiii",
      href: "https://youtube.com/@oxtobiiiii",
      cta: "Watch on YouTube",
      hint: "YouTube channel",
    },
  },
  inbox: "https://formsubmit.co/ajax/oxtobiiii@gmail.com",
  hireRoles: [
    "Web3 Creator",
    "Content Creator",
    "Community Manager",
    "Web3 Intern",
    "Community Contributor",
    "Ambassador",
    "KOL",
    "Collaboration",
    "Other",
  ] as const,
  lookingFor: [
    "Web3 Internship",
    "Content Creator",
    "Community Manager",
    "Ambassador",
    "KOL",
    "Project Collaboration",
  ],
  timeline: [
    { year: "2021", title: "Entered Web3", text: "Started learning ecosystems and CT." },
    { year: "2022–2024", title: "Building presence", text: "Content, community rooms, and ecosystem research." },
    { year: "2025–2026", title: "Creator & KOL", text: "Ambassador and KOL work with live campaigns." },
    { year: "Now", title: "Open for work", text: "Creator, community, intern, and collab roles." },
  ],
  services: [
    {
      n: "01",
      title: "Web3 Content",
      blurb: "CT posts, threads, and campaign content.",
      points: ["X / CT content", "Campaign posts", "Educational threads", "Engagement"],
    },
    {
      n: "02",
      title: "Community",
      blurb: "Discord / Telegram support and growth.",
      points: ["Community engagement", "Member support", "Feedback loops", "Room energy"],
    },
    {
      n: "03",
      title: "Ambassador / KOL",
      blurb: "Longer-term presence for products I use.",
      points: ["Campaign support", "Awareness", "Creator collabs", "Consistent posting"],
    },
    {
      n: "04",
      title: "Intern / Contributor",
      blurb: "Research, assistance, and follow-through.",
      points: ["Ecosystem research", "Content assist", "Community support", "Campaign help"],
    },
  ],
  heroCredLine: "Ambassador @ BestChange & Action Model · Official KOL @ Bitget Wallet",
  fightVideo: "/assets/obito-fight.webm",
  fightPoster: "/assets/dog-bg.jpg",
  ambassadors: [
    {
      name: "BestChange",
      handle: "bestchangeeng",
      href: "https://x.com/bestchangeeng",
      role: "Ambassador",
      summary: "Active ambassador.",
      logo: "/assets/partners/bestchange.jpg",
    },
    {
      name: "Action Model",
      handle: "ActionModelAI",
      href: "https://x.com/ActionModelAI",
      role: "Ambassador",
      summary: "Active ambassador.",
      logo: "/assets/partners/action-model.jpg",
    },
  ],
  kol: {
    name: "Bitget Wallet",
    handle: "BitgetWallet",
    href: "https://x.com/BitgetWallet",
    role: "Official KOL",
    summary: "Official KOL of Bitget Wallet.",
    logo: "/assets/partners/bitget-wallet.svg",
  },
  posts: [
    {
      tag: "YouTube",
      text: "Just opened the channel — first video, and a small giveaway for people who subscribed.",
      likes: "105",
      replies: "61",
      views: "3.2K",
      href: "https://x.com/ox_tobiiii/status/2103320225106346083",
    },
    {
      tag: "Community",
      text: "Thank you for the support. It feels like 3.7M YouTube subscribers already.",
      likes: "87",
      replies: "35",
      views: "2K",
      href: "https://x.com/ox_tobiiii/status/2103489513020641709",
    },
    {
      tag: "Safety",
      text: "Heads up: don’t drop your EVM address to accounts pushing random NFT links. Stay safe.",
      likes: "51",
      replies: "28",
      views: "2.1K",
      href: "https://x.com/ox_tobiiii/status/2103516479811703246",
    },
    {
      tag: "CT",
      text: "gm ct — part of Vinland.",
      likes: "136",
      replies: "113",
      views: "739",
      href: "https://x.com/ox_tobiiii/status/2103645866406092914",
    },
    {
      tag: "Collab",
      text: "Giving away Fomoki mint spots. Follow, like, RT, and tag two friends.",
      likes: "51",
      replies: "35",
      views: "477",
      href: "https://x.com/ox_tobiiii/status/2103684868521742677",
    },
    {
      tag: "CT",
      text: "Four months left in the year. Plan: cross $1,000 from X.",
      likes: "46",
      replies: "27",
      views: "407",
      href: "https://x.com/ox_tobiiii/status/2103678139151081840",
    },
  ],
  proof: [
    {
      project: "Action Model",
      excerpt: "NeoSoul campaign — train community-owned AI, earn, own it.",
      views: "7.6K",
      likes: "72",
      replies: "52",
      href: "https://x.com/ox_tobiiii/status/2097496137603432783",
    },
    {
      project: "CT",
      excerpt: "Live mint coverage: zecfrogs, Zeckers, zaddrnet, zentinels.",
      views: "5.2K",
      likes: "48",
      replies: "18",
      href: "https://x.com/ox_tobiiii/status/2101946032070516917",
    },
    {
      project: "ActionFi",
      excerpt: "SIXR weekend 2x points — $100K pool, top 200 leaderboard.",
      views: "3.2K",
      likes: "30",
      replies: "28",
      href: "https://x.com/ox_tobiiii/status/2096076254135128066",
    },
    {
      project: "Action Model",
      excerpt: "Marketplace in plain English — AI workflows, $LAM burns.",
      views: "2.1K",
      likes: "38",
      replies: "24",
      href: "https://x.com/ox_tobiiii/status/2097860326205395121",
    },
    {
      project: "ActionFi",
      excerpt: "40 lottery winners. NeoSoul + SIXR still live.",
      views: "1.8K",
      likes: "44",
      replies: "28",
      href: "https://x.com/ox_tobiiii/status/2096931947817881644",
    },
    {
      project: "ActionFi",
      excerpt: "ActionFi x SIXR guide — $100K pool, real product usage.",
      views: "1.7K",
      likes: "47",
      replies: "37",
      href: "https://x.com/ox_tobiiii/status/2095693778971664391",
    },
  ],
  statsNote: "Last 7 days · X Analytics",
  stats: [
    { label: "Followers", value: 15400, format: "compact" as const, note: "12.2K verified" },
    { label: "Impressions", value: 181000, format: "compact" as const, note: "+178%", tone: "up" as const },
    { label: "Engagements", value: 12900, format: "compact" as const, note: "+105%", tone: "up" as const },
    { label: "Engagement rate", value: 7.1, format: "percent" as const, note: "Last 7 days" },
  ],
  ecosystems: [
    "Arbitrum",
    "Aptos",
    "Sui",
    "LayerZero",
    "zkSync",
    "Linea",
    "Berachain",
    "Monad",
    "RedStone",
    "Ethereum",
    "Solana",
    "Base",
  ],
} as const;

export type HireRole = (typeof SITE.hireRoles)[number];

export const DEFAULT_FEATURED = [
  { id: "x", label: "View X Profile", href: SITE.contact.x.href, external: true },
  { id: "work", label: "Explore My Work", href: "#proof", external: false },
];
