/** Single place to edit Tobi's public identity, contact, and portfolio copy. */

export const SITE = {
  name: "Tobi",
  handle: "ox_tobiiii",
  title: "Tobi | Web3 Creator & Crypto Researcher",
  description:
    "Web3 creator, crypto researcher and AI enthusiast creating content, researching projects and collaborating with Web3 teams.",
  headline: "Web3 Creator. Researcher. Builder.",
  availability: "OPEN FOR WORK",
  availabilityNote: "OPEN TO OPPORTUNITIES",
  avatar: "/avatar.jpg",
  identities: ["Web3 Creator", "Crypto Researcher", "AI Enthusiast", "Artist", "Community Builder"],
  tagline: "Web3 Creator | Crypto Researcher | AI Enthusiast | Artist",
  heroSub: "I create content, research Web3 projects and help teams connect with the right audience.",
  heroBody: `I create content, research Web3 projects and help teams connect with the right audience.`,
  aboutTitle: "About",
  about: `I'm Tobi, a Web3 content creator and crypto researcher from Asia. I started exploring Web3 in 2021 and turned that curiosity into content, research, communities and collaborations.

I spend my time researching projects, creating content, testing products and talking to people who are actually building. Most of that happens on X and Telegram.

Projects come to me for content, promotion, KOL campaigns, threads, video and Spaces. I write in English. Most of the people reading are in Asia.`,
  creatorStats: [
    { value: "17.3K", label: "X followers" },
    { value: "13.8K", label: "Verified followers" },
    { value: "1M", label: "Impressions" },
    { value: "53.8K", label: "Engagements" },
    { value: "4.9%", label: "Engagement rate" },
  ],
  contact: {
    x: {
      label: "X / Twitter",
      handle: "ox_tobiiii",
      href: "https://x.com/ox_tobiiii",
      cta: "Message on X",
      hint: "Message me on X",
    },
    telegram: {
      label: "Telegram",
      handle: "@ox_tobiiii",
      href: "https://t.me/ox_tobiiii",
      cta: "Message on Telegram",
      hint: "Send me a Telegram message",
    },
    discord: {
      label: "Discord",
      handle: "ox_tobiiii",
      href: null as string | null,
      cta: "Copy Discord",
      hint: "Username — copy to clipboard",
    },
    email: {
      label: "Email",
      handle: "oxtobiiii@gmail.com",
      href: "mailto:oxtobiiii@gmail.com",
      cta: "Send Email",
      hint: "Send me an email",
    },
    youtube: {
      label: "YouTube",
      handle: "@oxtobiiiii",
      href: "https://youtube.com/@oxtobiiiii",
      cta: "Watch on YouTube",
      hint: "YouTube channel",
    },
  },
  onchain: {
    ens: null as string | null,
    address: null as string | null,
    explorer: null as string | null,
    explorerLabel: "Etherscan",
    talentHref: null as string | null,
    talentScore: null as string | null,
    passportHref: null as string | null,
    passportScore: null as string | null,
    farcaster: null as string | null,
    lens: null as string | null,
  },
  builders: [] as readonly { name: string; blurb: string; href: string }[],
  mediaKit: "/media-kit-tobi.pdf",
  statsUpdated: "26 Sep 2026",
  inbox: "https://formsubmit.co/ajax/oxtobiiii@gmail.com",
  hireRoles: [
    "Web3 Creator",
    "Content Creator",
    "Community Manager",
    "Web3 Intern",
    "Community Contributor",
    "Ambassador",
    "KOL",
    "Collaboration",
    "Other",
  ] as const,
  lookingFor: [
    "Web3 Internship",
    "Content Creator",
    "Community Manager",
    "Ambassador",
    "KOL",
    "Project Collaboration",
  ],
  timeline: [
    { year: "2021", title: "Started exploring Web3", text: "Learning ecosystems, crypto and CT." },
    { year: "2024", title: "Content and communities", text: "Writing, showing up in rooms, and following projects closely." },
    { year: "2025", title: "Working with projects", text: "Started earning through Web3 and taking creator work." },
    { year: "2026", title: "Creator presence", text: "Collaborations, campaigns and more consistent content." },
  ],
  whatIDo: [
    { title: "Content Creation", text: "Native Web3 content written for X and other socials." },
    { title: "Project Promotion", text: "Organic creator content that puts a project in front of a relevant audience." },
    { title: "KOL Campaigns", text: "Creator campaigns where the message still sounds like me." },
    { title: "Research", text: "Protocols, products, campaigns and the narratives forming around them." },
    { title: "Community Growth", text: "Connecting projects with people who are already active in Web3." },
    { title: "Video Content", text: "Short and long educational clips around projects and how they work." },
    { title: "X Spaces", text: "Join or host conversations around a project or a narrative." },
  ],
  offers: [
    { title: "Sponsored Posts", text: "A post on X about the project, in my voice." },
    { title: "X Replies", text: "Replies that add context where the conversation already is." },
    { title: "Quote Posts", text: "A quote post with a clear take, not a copy-paste line." },
    { title: "Threads", text: "A short thread that explains the product or the campaign." },
    { title: "Retweets", text: "Boost a post to people who already follow the work." },
    { title: "Video Content", text: "A short or long video walking through the idea." },
    { title: "Project Reviews", text: "A researched look at what the product actually does." },
    { title: "Campaign Promotion", text: "Support for a live campaign, quest or launch." },
    { title: "X Spaces", text: "A Space appearance or a hosted conversation." },
    { title: "Community Collaborations", text: "Show up with a community, not only a one-off post." },
  ],
  work: [
    {
      name: "BestChange",
      logo: "/assets/partners/bestchange.jpg",
      category: "Web3",
      description: "Crypto and e-money exchange aggregator.",
      role: "Ambassador",
      created: "Ongoing creator presence and campaign posts.",
      href: "https://x.com/bestchangeeng",
      post: null as string | null,
    },
    {
      name: "Action Model",
      logo: "/assets/partners/action-model.jpg",
      category: "AI",
      description: "Community-owned AI agents and workflows.",
      role: "Ambassador",
      created: "Explainers, campaign posts and short video.",
      href: "https://x.com/ActionModelAI",
      post: "https://x.com/ox_tobiiii/status/2097496137603432783",
    },
    {
      name: "Bitget Wallet",
      logo: "/assets/partners/bitget-wallet.svg",
      category: "DeFi",
      description: "Everyday finance wallet.",
      role: "Official KOL",
      created: "Creator coverage as an official KOL.",
      href: "https://x.com/BitgetWallet",
      post: "https://x.com/ox_tobiiii/status/2093968762974421086",
    },
    {
      name: "Echobit",
      logo: "/assets/partners/echobit.jpg",
      category: "Web3",
      description: "Global crypto exchange for futures.",
      role: "Ambassador",
      created: "Official creator.",
      href: "https://x.com/EchobitExchange",
      post: null as string | null,
    },
  ],
  faq: [
    {
      q: "How can I work with Tobi?",
      a: "DM on X, message on Telegram, or use the form. Say what the project is and what you need.",
    },
    {
      q: "What type of Web3 projects does Tobi work with?",
      a: "Web3, crypto, NFT, AI, DeFi and community-led products. If I don't use it or understand it, I'll say so.",
    },
    {
      q: "What content formats are available?",
      a: "Posts, replies, quote posts, threads, video, reviews and Spaces.",
    },
    {
      q: "Can Tobi participate in creator campaigns?",
      a: "Yes. KOL and launch campaigns are a normal part of the work.",
    },
    {
      q: "How can I request the media kit?",
      a: "Open the Media Kit page on this site, or email oxtobiiii@gmail.com.",
    },
    {
      q: "How can I contact Tobi?",
      a: "X @ox_tobiiii, Telegram @ox_tobiiii, or oxtobiiii@gmail.com.",
    },
  ],
  testimonials: [] as readonly { name: string; role: string; project: string; href: string; quote: string }[],
  services: [
    {
      n: "01",
      title: "Web3 Content",
      blurb: "CT posts, threads, and campaign content.",
      points: ["X / CT content", "Campaign posts", "Educational threads", "Engagement"],
    },
    {
      n: "02",
      title: "Community",
      blurb: "Discord / Telegram support and growth.",
      points: ["Community engagement", "Member support", "Feedback loops", "Room energy"],
    },
    {
      n: "03",
      title: "Ambassador / KOL",
      blurb: "Longer-term presence for products I use.",
      points: ["Campaign support", "Awareness", "Creator collabs", "Consistent posting"],
    },
    {
      n: "04",
      title: "Intern / Contributor",
      blurb: "Research, assistance, and follow-through.",
      points: ["Ecosystem research", "Content assist", "Community support", "Campaign help"],
    },
  ],
  heroCredLine: "Ambassador @ BestChange & Action Model · Official KOL @ Bitget Wallet",
  fightVideo: "/assets/obito-fight.webm",
  fightPoster: "/assets/dog-bg.jpg",
  ambassadors: [
    {
      name: "BestChange",
      handle: "bestchangeeng",
      href: "https://x.com/bestchangeeng",
      role: "Ambassador",
      summary: "Active ambassador.",
      logo: "/assets/partners/bestchange.jpg",
    },
    {
      name: "Action Model",
      handle: "ActionModelAI",
      href: "https://x.com/ActionModelAI",
      role: "Ambassador",
      summary: "Active ambassador.",
      logo: "/assets/partners/action-model.jpg",
    },
  ],
  kol: {
    name: "Bitget Wallet",
    handle: "BitgetWallet",
    href: "https://x.com/BitgetWallet",
    role: "Official KOL",
    summary: "Official KOL of Bitget Wallet.",
    logo: "/assets/partners/bitget-wallet.svg",
  },
  posts: [
    {
      tag: "Video",
      project: "Action Model",
      text: "From AI that generates to AI that acts. A short look at Action Model agents.",
      likes: "32",
      replies: "27",
      views: "2.8K",
      href: "https://x.com/ox_tobiiii/status/2103279495784620150",
    },
    {
      tag: "Guide",
      project: "Actionist",
      text: "How to build with Actionist — 13-step builder guidelines for workflows.",
      likes: "34",
      replies: "7",
      views: "1.3K",
      href: "https://x.com/ox_tobiiii/status/2102328225397649738",
    },
    {
      tag: "Guide",
      project: "ActionFi",
      text: "How to complete tasks with the ActionFi extension, without failing the click path.",
      likes: "33",
      replies: "16",
      views: "1.5K",
      href: "https://x.com/ox_tobiiii/status/2101134665969197342",
    },
    {
      tag: "Campaign",
      project: "SIXR × Action Model",
      text: "$100K pool still live until Oct 25. Leaderboard plus lottery, with $LAM along the way.",
      likes: "41",
      replies: "20",
      views: "716",
      href: "https://x.com/ox_tobiiii/status/2101906373416202514",
    },
    {
      tag: "Guide",
      project: "Zcash",
      text: "Simple Zcash wallet guide — Noir on desktop, mobile options, and which address to use.",
      likes: "44",
      replies: "19",
      views: "1.1K",
      href: "https://x.com/ox_tobiiii/status/2101878761532932390",
    },
    {
      tag: "Guide",
      project: "Orixians",
      text: "GTD whitelist steps: Discord, testnet pass, role, and how to avoid fake giveaways.",
      likes: "30",
      replies: "18",
      views: "1.6K",
      href: "https://x.com/ox_tobiiii/status/2097854852848365728",
    },
    {
      tag: "Campaign",
      project: "Action Model",
      text: "NeoSoul breakdown — train community-owned AI, earn it, own it.",
      likes: "72",
      replies: "52",
      views: "7.6K",
      href: "https://x.com/ox_tobiiii/status/2097496137603432783",
    },
    {
      tag: "Guide",
      project: "Action Model",
      text: "Marketplace in plain English — AI workflows, $LAM burns, and how creators get paid.",
      likes: "38",
      replies: "24",
      views: "2.1K",
      href: "https://x.com/ox_tobiiii/status/2097860326205395121",
    },
    {
      tag: "Guide",
      project: "ActionFi × SIXR",
      text: "Campaign guide: $100K pool, $LAM farming, and real product tasks — not empty follows.",
      likes: "47",
      replies: "37",
      views: "1.7K",
      href: "https://x.com/ox_tobiiii/status/2095693778971664391",
    },
    {
      tag: "Campaign",
      project: "ActionFi",
      text: "Weekend 2x points on SIXR daily tasks. $100K pool, top 200 on the board.",
      likes: "30",
      replies: "28",
      views: "3.2K",
      href: "https://x.com/ox_tobiiii/status/2096076254135128066",
    },
  ],
  nftGiveaways: [
    { project: "Fomoki", spots: "5 mint spots", date: "26 Sep 2026", href: "https://x.com/ox_tobiiii/status/2103684868521742677" },
    { project: "Zecfrogs", spots: "10x GTD", date: "21 Sep 2026", href: "https://x.com/ox_tobiiii/status/2101887065269137818" },
    { project: "Zeckers", spots: "5x GTD", date: "19 Sep 2026", href: "https://x.com/ox_tobiiii/status/2101222847431794997" },
    { project: "Zecfrogs", spots: "10x GTD", date: "18 Sep 2026", href: "https://x.com/ox_tobiiii/status/2100970019459060056" },
    { project: "Bunny WTF", spots: "20x GTD", date: "17 Sep 2026", href: "https://x.com/ox_tobiiii/status/2100588855414129060" },
    { project: "Obsession", spots: "5x GTD", date: "17 Sep 2026", href: "https://x.com/ox_tobiiii/status/2100489931550495212" },
    { project: "Arc Tellers", spots: "3 GTD + 10 FCFS", date: "16 Sep 2026", href: "https://x.com/ox_tobiiii/status/2100150246835933187" },
    { project: "Hizumi, Kashed, Turtz", spots: "8 / 20 / 10 GTD", date: "16 Sep 2026", href: "https://x.com/ox_tobiiii/status/2100120623792247079" },
    { project: "Hazels", spots: "5x WL", date: "16 Sep 2026", href: "https://x.com/ox_tobiiii/status/2100103430975144360" },
    { project: "Arc Cat", spots: "10 GTD", date: "15 Sep 2026", href: "https://x.com/ox_tobiiii/status/2099734535160426664" },
    { project: "Imprint", spots: "1x GTD", date: "10 Sep 2026", href: "https://x.com/ox_tobiiii/status/2098087967499964540" },
    { project: "SexyHood", spots: "3 GTD", date: "1 Sep 2026", href: "https://x.com/ox_tobiiii/status/2094667439611302291" },
    { project: "Proof of Pixels", spots: "5 GTD", date: "27 Aug 2026", href: "https://x.com/ox_tobiiii/status/2092887973599584555" },
  ],
  proof: [
    {
      project: "Action Model",
      excerpt: "NeoSoul campaign — train community-owned AI, earn, own it.",
      views: "7.6K",
      likes: "72",
      replies: "52",
      href: "https://x.com/ox_tobiiii/status/2097496137603432783",
    },
    {
      project: "CT",
      excerpt: "Live mint coverage: zecfrogs, Zeckers, zaddrnet, zentinels.",
      views: "5.2K",
      likes: "48",
      replies: "18",
      href: "https://x.com/ox_tobiiii/status/2101946032070516917",
    },
    {
      project: "ActionFi",
      excerpt: "SIXR weekend 2x points — $100K pool, top 200 leaderboard.",
      views: "3.2K",
      likes: "30",
      replies: "28",
      href: "https://x.com/ox_tobiiii/status/2096076254135128066",
    },
    {
      project: "Action Model",
      excerpt: "Marketplace in plain English — AI workflows, $LAM burns.",
      views: "2.1K",
      likes: "38",
      replies: "24",
      href: "https://x.com/ox_tobiiii/status/2097860326205395121",
    },
    {
      project: "ActionFi",
      excerpt: "40 lottery winners. NeoSoul + SIXR still live.",
      views: "1.8K",
      likes: "44",
      replies: "28",
      href: "https://x.com/ox_tobiiii/status/2096931947817881644",
    },
    {
      project: "ActionFi",
      excerpt: "ActionFi x SIXR guide — $100K pool, real product usage.",
      views: "1.7K",
      likes: "47",
      replies: "37",
      href: "https://x.com/ox_tobiiii/status/2095693778971664391",
    },
  ],
  analytics: {
    source: "X analytics",
    ranges: [
      {
        id: "14d",
        label: "14 days",
        items: [
          { value: "409.2K", label: "Impressions", change: "+267%", up: true },
          { value: "6.4%", label: "Engagement rate", change: "−30%", up: false },
          { value: "26.5K", label: "Engagements", change: "+154%", up: true },
          { value: "4.2K", label: "Profile visits", change: "+171%", up: true },
        ],
      },
      {
        id: "3m",
        label: "3 months",
        items: [
          { value: "1M", label: "Impressions", change: null, up: true },
          { value: "4.9%", label: "Engagement rate", change: null, up: true },
          { value: "53.8K", label: "Engagements", change: null, up: true },
          { value: "8.7K", label: "Profile visits", change: null, up: true },
        ],
      },
    ],
  },
  statsNote: "X Analytics",
  stats: [
    { label: "Followers", value: 17300, format: "compact" as const, note: "13.8K verified · 14.6K active" },
    { label: "Impressions", value: 1000000, format: "compact" as const },
    { label: "Engagements", value: 53800, format: "compact" as const },
    { label: "Engagement rate", value: 4.9, format: "percent" as const },
    { label: "Replies", value: 15700, format: "compact" as const },
    { label: "Likes", value: 27200, format: "compact" as const },
    { label: "Profile visits", value: 8700, format: "compact" as const },
    { label: "Reposts", value: 1700, format: "compact" as const },
  ],
  ecosystems: [
    { name: "Ethereum", logo: "/assets/eco/ethereum.svg" },
    { name: "Solana", logo: "/assets/eco/solana.svg" },
    { name: "Arbitrum", logo: "/assets/eco/arbitrum.svg" },
    { name: "Base", logo: "/assets/eco/base.svg" },
    { name: "Aptos", logo: "/assets/eco/aptos.svg" },
    { name: "Sui", logo: "/assets/eco/sui.svg" },
    { name: "LayerZero", logo: "/assets/eco/layerzero.svg" },
    { name: "zkSync", logo: "/assets/eco/zksync.svg" },
    { name: "Linea", logo: "/assets/eco/linea.svg" },
    { name: "Berachain", logo: "/assets/eco/berachain.svg" },
    { name: "Monad", logo: "/assets/eco/monad.svg" },
    { name: "Story Protocol", logo: "/assets/eco/story.svg" },
    { name: "RedStone", logo: "/assets/eco/redstone.svg" },
  ],
} as const;

export type HireRole = (typeof SITE.hireRoles)[number];

export const DEFAULT_FEATURED = [
  { id: "x", label: "View X Profile", href: SITE.contact.x.href, external: true },
  { id: "work", label: "Explore My Work", href: "#proof", external: false },
];
