/** Single place to edit Tobi's public identity, contact, and portfolio copy. */

export const SITE = {
  name: "Tobi",
  handle: "ox_tobiiii",
  title: "Tobi — Web3 Creator | Community | Content",
  description:
    "Web3 creator and community contributor. Ambassador at BestChange & Action Model. Official KOL at Bitget Wallet.",
  headline: "Web3 Creator, CT & Community",
  availability: "OPEN FOR WORK",
  availabilityNote: "OPEN TO OPPORTUNITIES",
  avatar: "/avatar.jpg",
  identities: [
    "Web3 Creator",
    "Content Creator",
    "Community Manager",
    "Ambassador",
    "KOL",
  ],
  tagline: "Web3 Creator • Content Creator • Community Manager",
  heroBody: `In Web3 since 2021. I make CT content, help communities grow, and work with teams as a creator, ambassador, and KOL.

Open for creator roles, community roles, internships, ambassador work, and collaborations.`,
  aboutTitle: "Who is Tobi?",
  about: `Started in Web3 in 2021 by learning ecosystems and following CT.

Now I ship content, show up in communities, and represent products I actually use — BestChange, Action Model, and Bitget Wallet.

Looking for teams that need a creator who can write, engage, and stay consistent.`,
  contact: {
    x: {
      label: "X / Twitter",
      handle: "ox_tobiiii",
      href: "https://x.com/ox_tobiiii",
      cta: "Message on X",
      hint: "Message me on X",
    },
    telegram: {
      label: "Telegram",
      handle: "@ox_tobiiii",
      href: "https://t.me/ox_tobiiii",
      cta: "Message on Telegram",
      hint: "Send me a Telegram message",
    },
    discord: {
      label: "Discord",
      handle: "ox_tobiiii",
      href: null as string | null,
      cta: "Copy Discord",
      hint: "Username — copy to clipboard",
    },
    email: {
      label: "Email",
      handle: "oxtobiiii@gmail.com",
      href: "mailto:oxtobiiii@gmail.com",
      cta: "Send Email",
      hint: "Send me an email",
    },
    youtube: {
      label: "YouTube",
      handle: "@oxtobiiiii",
      href: "https://youtube.com/@oxtobiiiii",
      cta: "Watch on YouTube",
      hint: "YouTube channel",
    },
  },
  inbox: "https://formsubmit.co/ajax/oxtobiiii@gmail.com",
  hireRoles: [
    "Web3 Creator",
    "Content Creator",
    "Community Manager",
    "Web3 Intern",
    "Community Contributor",
    "Ambassador",
    "KOL",
    "Collaboration",
    "Other",
  ] as const,
  lookingFor: [
    "Web3 Internship",
    "Content Creator",
    "Community Manager",
    "Ambassador",
    "KOL",
    "Project Collaboration",
  ],
  timeline: [
    { year: "2021", title: "Entered Web3", text: "Started learning ecosystems and CT." },
    { year: "2022–2024", title: "Building presence", text: "Content, community rooms, and ecosystem research." },
    { year: "2025–2026", title: "Creator & KOL", text: "Ambassador and KOL work with live campaigns." },
    { year: "Now", title: "Open for work", text: "Creator, community, intern, and collab roles." },
  ],
  services: [
    {
      n: "01",
      title: "Web3 Content",
      blurb: "CT posts, threads, and campaign content.",
      points: ["X / CT content", "Campaign posts", "Educational threads", "Engagement"],
    },
    {
      n: "02",
      title: "Community",
      blurb: "Discord / Telegram support and growth.",
      points: ["Community engagement", "Member support", "Feedback loops", "Room energy"],
    },
    {
      n: "03",
      title: "Ambassador / KOL",
      blurb: "Longer-term presence for products I use.",
      points: ["Campaign support", "Awareness", "Creator collabs", "Consistent posting"],
    },
    {
      n: "04",
      title: "Intern / Contributor",
      blurb: "Research, assistance, and follow-through.",
      points: ["Ecosystem research", "Content assist", "Community support", "Campaign help"],
    },
  ],
  heroCredLine: "Ambassador @ BestChange & Action Model · Official KOL @ Bitget Wallet",
  fightVideo: "/assets/obito-fight.webm",
  fightPoster: "/assets/dog-bg.jpg",
  ambassadors: [
    {
      name: "BestChange",
      handle: "bestchangeeng",
      href: "https://x.com/bestchangeeng",
      role: "Ambassador",
      summary: "Active ambassador.",
      logo: "/assets/partners/bestchange.jpg",
    },
    {
      name: "Action Model",
      handle: "ActionModelAI",
      href: "https://x.com/ActionModelAI",
      role: "Ambassador",
      summary: "Active ambassador.",
      logo: "/assets/partners/action-model.jpg",
    },
  ],
  kol: {
    name: "Bitget Wallet",
    handle: "BitgetWallet",
    href: "https://x.com/BitgetWallet",
    role: "Official KOL",
    summary: "Official KOL of Bitget Wallet.",
    logo: "/assets/partners/bitget-wallet.svg",
  },
  posts: [
    {
      tag: "Video",
      project: "Action Model",
      text: "From AI that generates to AI that acts. A short look at Action Model agents.",
      likes: "32",
      replies: "27",
      views: "2.8K",
      href: "https://x.com/ox_tobiiii/status/2103279495784620150",
    },
    {
      tag: "Guide",
      project: "Actionist",
      text: "How to build with Actionist — 13-step builder guidelines for workflows.",
      likes: "34",
      replies: "7",
      views: "1.3K",
      href: "https://x.com/ox_tobiiii/status/2102328225397649738",
    },
    {
      tag: "Guide",
      project: "ActionFi",
      text: "How to complete tasks with the ActionFi extension, without failing the click path.",
      likes: "33",
      replies: "16",
      views: "1.5K",
      href: "https://x.com/ox_tobiiii/status/2101134665969197342",
    },
    {
      tag: "Campaign",
      project: "SIXR × Action Model",
      text: "$100K pool still live until Oct 25. Leaderboard plus lottery, with $LAM along the way.",
      likes: "41",
      replies: "20",
      views: "716",
      href: "https://x.com/ox_tobiiii/status/2101906373416202514",
    },
    {
      tag: "Guide",
      project: "Zcash",
      text: "Simple Zcash wallet guide — Noir on desktop, mobile options, and which address to use.",
      likes: "44",
      replies: "19",
      views: "1.1K",
      href: "https://x.com/ox_tobiiii/status/2101878761532932390",
    },
    {
      tag: "Guide",
      project: "Orixians",
      text: "GTD whitelist steps: Discord, testnet pass, role, and how to avoid fake giveaways.",
      likes: "30",
      replies: "18",
      views: "1.6K",
      href: "https://x.com/ox_tobiiii/status/2097854852848365728",
    },
    {
      tag: "Campaign",
      project: "Action Model",
      text: "NeoSoul breakdown — train community-owned AI, earn it, own it.",
      likes: "72",
      replies: "52",
      views: "7.6K",
      href: "https://x.com/ox_tobiiii/status/2097496137603432783",
    },
    {
      tag: "Guide",
      project: "Action Model",
      text: "Marketplace in plain English — AI workflows, $LAM burns, and how creators get paid.",
      likes: "38",
      replies: "24",
      views: "2.1K",
      href: "https://x.com/ox_tobiiii/status/2097860326205395121",
    },
    {
      tag: "Guide",
      project: "ActionFi × SIXR",
      text: "Campaign guide: $100K pool, $LAM farming, and real product tasks — not empty follows.",
      likes: "47",
      replies: "37",
      views: "1.7K",
      href: "https://x.com/ox_tobiiii/status/2095693778971664391",
    },
    {
      tag: "Campaign",
      project: "ActionFi",
      text: "Weekend 2x points on SIXR daily tasks. $100K pool, top 200 on the board.",
      likes: "30",
      replies: "28",
      views: "3.2K",
      href: "https://x.com/ox_tobiiii/status/2096076254135128066",
    },
  ],
  proof: [
    {
      project: "Action Model",
      excerpt: "NeoSoul campaign — train community-owned AI, earn, own it.",
      views: "7.6K",
      likes: "72",
      replies: "52",
      href: "https://x.com/ox_tobiiii/status/2097496137603432783",
    },
    {
      project: "CT",
      excerpt: "Live mint coverage: zecfrogs, Zeckers, zaddrnet, zentinels.",
      views: "5.2K",
      likes: "48",
      replies: "18",
      href: "https://x.com/ox_tobiiii/status/2101946032070516917",
    },
    {
      project: "ActionFi",
      excerpt: "SIXR weekend 2x points — $100K pool, top 200 leaderboard.",
      views: "3.2K",
      likes: "30",
      replies: "28",
      href: "https://x.com/ox_tobiiii/status/2096076254135128066",
    },
    {
      project: "Action Model",
      excerpt: "Marketplace in plain English — AI workflows, $LAM burns.",
      views: "2.1K",
      likes: "38",
      replies: "24",
      href: "https://x.com/ox_tobiiii/status/2097860326205395121",
    },
    {
      project: "ActionFi",
      excerpt: "40 lottery winners. NeoSoul + SIXR still live.",
      views: "1.8K",
      likes: "44",
      replies: "28",
      href: "https://x.com/ox_tobiiii/status/2096931947817881644",
    },
    {
      project: "ActionFi",
      excerpt: "ActionFi x SIXR guide — $100K pool, real product usage.",
      views: "1.7K",
      likes: "47",
      replies: "37",
      href: "https://x.com/ox_tobiiii/status/2095693778971664391",
    },
  ],
  statsNote: "Last 7 days · X Analytics",
  stats: [
    { label: "Followers", value: 15400, format: "compact" as const, note: "12.2K verified" },
    { label: "Impressions", value: 181000, format: "compact" as const, note: "+178%", tone: "up" as const },
    { label: "Engagements", value: 12900, format: "compact" as const, note: "+105%", tone: "up" as const },
    { label: "Engagement rate", value: 7.1, format: "percent" as const, note: "Last 7 days" },
  ],
  ecosystems: [
    { name: "Ethereum", logo: "/assets/eco/ethereum.svg" },
    { name: "Solana", logo: "/assets/eco/solana.svg" },
    { name: "Arbitrum", logo: "/assets/eco/arbitrum.svg" },
    { name: "Base", logo: "/assets/eco/base.svg" },
    { name: "Aptos", logo: "/assets/eco/aptos.svg" },
    { name: "Sui", logo: "/assets/eco/sui.svg" },
    { name: "LayerZero", logo: "/assets/eco/layerzero.svg" },
    { name: "zkSync", logo: "/assets/eco/zksync.svg" },
    { name: "Linea", logo: "/assets/eco/linea.svg" },
    { name: "Berachain", logo: "/assets/eco/berachain.svg" },
    { name: "Monad", logo: "/assets/eco/monad.svg" },
    { name: "RedStone", logo: "/assets/eco/redstone.svg" },
  ],
} as const;

export type HireRole = (typeof SITE.hireRoles)[number];

export const DEFAULT_FEATURED = [
  { id: "x", label: "View X Profile", href: SITE.contact.x.href, external: true },
  { id: "work", label: "Explore My Work", href: "#proof", external: false },
];
